### ISSUE TITLE
Exception: cannot import name 'safe_str_cmp' from 'werkzeug.security' (Flask-Login v0.6.0)

### ISSUE THREAD

**Issue by KrennKristof** [wuttem/flask-ad-auth#5]
Similar to the existing issue [3](https://github.com/wuttem/flask-ad-auth/issues/3) since Flask-Login version 0.6.0 I get the error "cannot import name 'safe_str_cmp' from 'werkzeug.security'" because werkzeug was updated too.

Traceback:

`    from flask_ad_auth import current_user
../lib/python3.8/site-packages/flask_ad_auth/__init__.py:4: in <module>
    from flask_login import (
../lib/python3.8/site-packages/flask_login/__init__.py:16: in <module>
    from .login_manager import LoginManager
../lib/python3.8/site-packages/flask_login/login_manager.py:24: in <module>
    from .utils import (_get_user, login_url as make_login_url, _create_identifier,
../lib/python3.8/site-packages/flask_login/utils.py:13: in <module>
    from werkzeug.security import safe_str_cmp
E   ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security' (/lib/python3.8/site-packages/werkzeug/security.py)
`

Please update flask-ad-auth to use the newest versions of Flask, Flask-Login and Werkzeug.

**Comment by wuttem** [comment]
Can you check if this is fixed with v0.8 ?
